### PR TITLE
GWTII-266: enable full compile, specifically for IE11

### PR DESCRIPTION
**Pull request by janvenstermans**

### CODE REVIEW

**Comment by janvenstermans** [comment]
compare in IE11:
http://dev.geomajas.org/geomajas-client-gwt2-example-2.2.1-SNAPSHOT/
http://dev.geomajas.org/geomajas-client-gwt2-example-GWTII-266_IE11/

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by jandm** [comment]
+1 (binding)

**Pull request merged**
