### PR TITLE
MAJ-1181: bugfix filter of geomajasContext*.xml

### PR DESCRIPTION
**Pull request by janvenstermans**

### CODE REVIEW

**Comment by janvenstermans** [comment]
as a test: run on Jenkins:  http://ci.geomajas.org/jenkins/job/Geomajas%20Project%20GWT2%20client%20MAJ-1181/3/
has same result as master branch http://ci.geomajas.org/jenkins/job/Geomajas%20Project%20GWT2%20client/441/

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by hkristof** [comment]
kristof: +1 (binding) 
= _ =

**Comment by dosi-bingov** [comment]
Dosi: +1

**Comment by pieterdg** [comment]
+1

**Comment by janvenstermans** [comment]
Vote count: 
Kristof Heirwegh: +1 (binding)
Pieter De Graef: +1 (binding)
Dosi Bingov: +1
Jan Venstermans: +1

vote is successful

**Pull request merged**
