### PR TITLE
GWTII-297: after dragging, make sure an event with a non-dragging View is fired

### PR DESCRIPTION
**Pull request by janvenstermans**

### CODE REVIEW

**Comment by jandm** [comment]
+1 (binding)

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by janvenstermans** [comment]
Vote count:
Jan De Moerlosse: +1 (binding)
Oliver May: +1 (binding)

Jan Venstermans: +1

vote successful

**Pull request merged**
