### PR TITLE
GWTII-276: show starting vertice

### PR DESCRIPTION
**Pull request by hkristof**

### CODE REVIEW

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

(I guess the build failure is due to limited memory on travis, still needs to be fixed)

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by jandm** [comment]
Jan De Moerloose: +1 (binding)

**Comment by janvenstermans** [comment]
Vote successful:
Jan De Moerloose: +1 (binding)
Oliver May: +1 (binding)

Jan Venstermans: +1

**Pull request merged**
