### PR TITLE
GWTII-277: make geocoder widget css classes visible + set position via css

### PR DESCRIPTION
**Pull request by janvenstermans**
Example at http://dev.geomajas.org/geomajas-client-gwt2-example-for-GWTII-277_geocoderWidgetStyling/?sample=geocoder

Documentation update: 
http://dev.geomajas.org/docbkx-for-GWTII-277_geocoderWidgetStyling/html/master.html
(compare with current http://files.geomajas.org/documentation/geomajas-project-client-gwt2/2.2.0/geomajas-client-gwt2-plugin-geocoder-documentation/html/master.html)

### CODE REVIEW

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by jandm** [comment]
Jan De Moerloose: +1 (binding)

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by janvenstermans** [comment]
Vote successful: 
Jan De Moerloose: +1 (binding)
Oliver May: +1 (binding)

Jan Venstermans: +1

travis build fails generally on this project

**Pull request merged**
