### PR TITLE
GWTII-281: Make clearSelectedFeatures() method of VectorServerLayerImpl ...

### PR DESCRIPTION
**Pull request by janvenstermans**
...consistent with other add/remove - event procedures. At any moment, event follows the change of model.

### CODE REVIEW

**Comment by janvenstermans** [comment]
Jan Venstermans:+1

**Comment by jandm** [comment]
Jan De Moerloose: +1 (binding)

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by janvenstermans** [comment]
Vote successful:
Jan De Moerloose: +1 (binding)
Oliver May: +1 (binding)

Jan Venstermans:+1

**Pull request merged**
