### PR TITLE
Jandm gwtii 289 touch

### PR DESCRIPTION
**Pull request by jandm**
Adds support for pointer events by converting to touch equivalents (pointer events have no history of previous events).

### CODE REVIEW

**Comment by jandm** [comment]
Jan De Moerloose: +1 (binding)

**Comment by janvenstermans** [comment]
Jan Venstermans: +1
Although I would prefer if all commits would be squashed into one commit.

**Comment by geohubtest** [comment]
Tested GWTII-289 on Internet Explorer 11 touch and works as expected

**Comment by oliverm-be** [comment]
+1 (binding)

**Pull request merged**
