### PR TITLE
GWTII-267: remove server dependency from core widget plugin

### PR DESCRIPTION
**Pull request by janvenstermans**
local "mvn clean install" successful

Server dependency was used in LayerControlPanelPresenterImpl  of layercontrolpanel widget.

!!!!  API CHANGE: added methods to Layer interface.
Added a LayerUtil class to impl module

### CODE REVIEW

**Comment by janvenstermans** [comment]
There was no example for LayerControlPanelPresenterImpl  I think, needs to be added.

**Comment by janvenstermans** [comment]
Example of resolution ranges:
http://dev.geomajas.org/geomajas-client-gwt2-example-GWTII-267_corewidgetDependency_addExample/?sample=maplegendlayerresolutionrange

**Comment by janvenstermans** [comment]
Please review in detail, api changes for Layer interface. @since annotation filled for next major release

**Comment by janvenstermans** [comment]
Jan Venstermans : +1

**Comment by jandm** [comment]
+1: binding

**Comment by oliverm-be** [comment]
@pieterdg can you check if this is ok?

**Comment by pieterdg** [comment]
Jan, overall a nice proposal. The only thing that bugs me is the LayerUtil. In general the use of utils classes should be avoided. I believe you could add the method in question to the AbstractLayer instead. If we want this method to be API, we could even add it to the ViewPort interface...

For now I would suggest adding it to the AbstractLayer class, and deleting the util class.

**Comment by janvenstermans** [comment]
Changed code:
* added incl/exclusive SLD rules to the Layer interface.
* AbstractLayer has public method "boolean isVisibleAtViewPortResolution(ViewPort viewPort)"
* LayerControlPanelPresenterImpl also has the code for "isLayerVisibleAtViewPortResolution": this is some code duplication, but alternative would have been to change variable Layer (interface) to variable AbstractLayer (class). Not all Layer instances are AbstractLayer.
* removes LayerUtil and its test class.

**Comment by pieterdg** [comment]
+1 binding

**Comment by janvenstermans** [comment]
travis build failure because of new Layer implementation in current master (SimpleWfsLayer ). Needs rebase before merging.

**Pull request merged**
